name: 'Contact Form'
core: 8.x
type: module
package: Lightning
description: 'Provides a site-wide contact form with basic default configuration.'
dependencies:
  - contact_storage:contact_storage

# Information added by Drupal.org packaging script on 2019-09-27
version: '8.x-4.7'
project: 'lightning_core'
datestamp: 1569615492
