name: 'Lightning Search'
core: 8.x
type: module
package: Lightning
description: 'A basic but powerful set of default configuration for searching your site.'
dependencies:
  - lightning_core:lightning_core
  - search_api:search_api
  - drupal:views

# Information added by Drupal.org packaging script on 2019-09-27
version: '8.x-4.7'
project: 'lightning_core'
datestamp: 1569615492
