name: 'Lightning Layout'
# core: 8.x
type: module
description: 'Provides the tools to take control of your layout.'
package: Lightning
dependencies:
  - drupal:block
  - drupal:layout_builder
  - drupal:options
  - layout_builder_st:layout_builder_st
  - layout_library:layout_library
  - layout_builder_restrictions:layout_builder_restrictions
  - lightning_core:lightning_core
components:
  - lightning_banner_block
  - lightning_landing_page
  - lightning_map_block

# Information added by Drupal.org packaging script on 2019-06-25
version: '8.x-2.1'
core: '8.x'
project: 'lightning_layout'
datestamp: 1561486387
