name: 'Media Video'
# core: 8.x
type: module
package: Lightning
description: 'Video support for Lightning Media.'
dependencies:
  - lightning_media:lightning_media
  - video_embed_field:video_embed_media

# Information added by Drupal.org packaging script on 2019-06-26
version: '8.x-3.12'
core: '8.x'
project: 'lightning_media'
datestamp: 1561582990
